# Generated by Django 5.2.16 on 2026-07-14 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('trigger', models.CharField(default='manual', max_length=30, verbose_name='Способ запуска')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Запуск сбора',
                'verbose_name_plural': 'Запуски сбора',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('nights', models.PositiveSmallIntegerField(verbose_name='Ночей')),
                ('adults', models.PositiveSmallIntegerField(verbose_name='Взрослых')),
                ('children_ages', models.JSONField(blank=True, default=list, verbose_name='Возраст детей')),
                ('transfer_included', models.BooleanField(verbose_name='Трансфер включён')),
                ('taxes_included', models.BooleanField(verbose_name='Налоги включены')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('best_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Лучшая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.hotel', verbose_name='Отель')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.mealplan', verbose_name='Питание')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.roomcategory', verbose_name='Категория номера')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_groups', to='pricing.collectionrun', verbose_name='Запуск')),
            ],
            options={
                'verbose_name': 'Группа сравнения',
                'verbose_name_plural': 'Группы сравнения',
                'ordering': ('hotel__canonical_name', 'room_category__canonical_name'),
            },
        ),
        migrations.CreateModel(
            name='PriceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('nights', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ночей')),
                ('adults', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Взрослых')),
                ('children_ages', models.JSONField(blank=True, default=list, verbose_name='Возраст детей')),
                ('transfer_included', models.BooleanField(default=False, verbose_name='Трансфер включён')),
                ('taxes_included', models.BooleanField(default=True, verbose_name='Налоги включены')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('included_components', models.JSONField(blank=True, default=dict, verbose_name='Состав цены')),
                ('offer_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Исходный ответ')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.hotel', verbose_name='Единый отель')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.mealplan', verbose_name='Питание')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.roomcategory', verbose_name='Единая категория')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='pricing.collectionrun', verbose_name='Запуск')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.source', verbose_name='Источник')),
                ('source_hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.sourcehotel', verbose_name='Отель у источника')),
                ('source_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='catalog.sourceroomcategory', verbose_name='Номер у источника')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('-captured_at',),
            },
        ),
        migrations.CreateModel(
            name='ComparisonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_difference', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Разница в валюте')),
                ('percent_difference', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Разница в процентах')),
                ('color_status', models.CharField(choices=[('green', 'Лучшая цена'), ('yellow', 'До 5%'), ('orange', 'От 5% до 10%'), ('red', 'Более 10%')], max_length=10, verbose_name='Цвет')),
                ('is_best', models.BooleanField(default=False, verbose_name='Лучшая цена')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.comparisongroup', verbose_name='Группа')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_item', to='pricing.priceoffer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Результат сравнения',
                'verbose_name_plural': 'Результаты сравнения',
                'ordering': ('offer__price',),
            },
        ),
        migrations.AddField(
            model_name='comparisongroup',
            name='best_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='best_for_groups', to='pricing.priceoffer', verbose_name='Лучшая цена'),
        ),
        migrations.CreateModel(
            name='SearchScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('destination', models.CharField(default='Сейшелы', max_length=150, verbose_name='Направление')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('nights', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество ночей')),
                ('adults', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Взрослых')),
                ('children_ages', models.JSONField(blank=True, default=list, verbose_name='Возраст детей')),
                ('include_flight', models.BooleanField(default=False, verbose_name='Включать перелёт')),
                ('include_transfer', models.BooleanField(default=False, verbose_name='Включать трансфер')),
                ('first_available_only', models.BooleanField(default=True, verbose_name='Только первая доступная категория')),
                ('preferred_currency', models.CharField(default='USD', max_length=3, verbose_name='Валюта сравнения')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hotels', models.ManyToManyField(blank=True, related_name='search_scenarios', to='catalog.hotel', verbose_name='Отели')),
            ],
            options={
                'verbose_name': 'Сценарий поиска',
                'verbose_name_plural': 'Сценарии поиска',
                'ordering': ('-check_in', 'name'),
            },
        ),
        migrations.AddField(
            model_name='collectionrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='pricing.searchscenario', verbose_name='Сценарий'),
        ),
        migrations.AddIndex(
            model_name='priceoffer',
            index=models.Index(fields=['run', 'hotel', 'room_category', 'meal_plan'], name='offer_compare_idx'),
        ),
    ]
