# Generated by Django 5.2.16 on 2026-07-14 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип питания',
                'verbose_name_plural': 'Типы питания',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('base_url', models.URLField(blank=True, verbose_name='Адрес сайта')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включён')),
            ],
            options={
                'verbose_name': 'Источник',
                'verbose_name_plural': 'Источники',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Сейшелы', max_length=100, verbose_name='Страна')),
                ('destination', models.CharField(blank=True, max_length=150, verbose_name='Курорт/остров')),
                ('canonical_name', models.CharField(max_length=255, verbose_name='Единое название')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ('canonical_name',),
                'constraints': [models.UniqueConstraint(fields=('country', 'canonical_name'), name='uniq_hotel_country_name')],
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, verbose_name='Единое название категории')),
                ('active', models.BooleanField(default=True, verbose_name='Активна')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='catalog.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
                'ordering': ('hotel__canonical_name', 'canonical_name'),
            },
        ),
        migrations.CreateModel(
            name='SourceHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Название на сайте')),
                ('source_code', models.CharField(blank=True, max_length=255, verbose_name='ID на сайте')),
                ('match_status', models.CharField(choices=[('auto', 'Сопоставлено автоматически'), ('confirmed', 'Подтверждено вручную'), ('review', 'Требует проверки'), ('ignore', 'Не сопоставлять')], default='review', max_length=20, verbose_name='Статус сопоставления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_names', to='catalog.hotel', verbose_name='Единый отель')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_hotels', to='catalog.source', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Название отеля у источника',
                'verbose_name_plural': 'Названия отелей у источников',
                'ordering': ('source__name', 'source_name'),
            },
        ),
        migrations.CreateModel(
            name='SourceRoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, verbose_name='Название категории на сайте')),
                ('source_code', models.CharField(blank=True, max_length=255, verbose_name='ID категории на сайте')),
                ('match_status', models.CharField(choices=[('auto', 'Сопоставлено автоматически'), ('confirmed', 'Подтверждено вручную'), ('review', 'Требует проверки'), ('ignore', 'Не сопоставлять')], default='review', max_length=20, verbose_name='Статус сопоставления')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_names', to='catalog.roomcategory', verbose_name='Единая категория')),
                ('source_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_rooms', to='catalog.sourcehotel', verbose_name='Отель у источника')),
            ],
            options={
                'verbose_name': 'Категория номера у источника',
                'verbose_name_plural': 'Категории номеров у источников',
                'ordering': ('source_hotel__source__name', 'source_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='roomcategory',
            constraint=models.UniqueConstraint(fields=('hotel', 'canonical_name'), name='uniq_room_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='sourcehotel',
            constraint=models.UniqueConstraint(fields=('source', 'source_name'), name='uniq_source_hotel_name'),
        ),
        migrations.AddConstraint(
            model_name='sourceroomcategory',
            constraint=models.UniqueConstraint(fields=('source_hotel', 'source_name'), name='uniq_source_room_name'),
        ),
    ]
