# Generated by Django 5.2.16 on 2026-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotels/', verbose_name='Сжатое фото'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_page_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Страница — источник фото'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_source_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Прямая ссылка на исходное фото'),
        ),
        migrations.AddField(
            model_name='sourcehotel',
            name='detail_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Страница отеля у источника'),
        ),
        migrations.AddField(
            model_name='sourcehotel',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Фото отеля у источника'),
        ),
    ]
